### ISSUE TITLE
Amazing library, but onFailed should return a message not an errorCode

### ISSUE THREAD

**Issue by AbGhost-cyber** [tejmagar/AndroidWiFiTools#2]
onFailed should return a message so we can get to know what's really wrong, i think errorCode is not clear, also i tested this on a printer, an apple and a huawei devices but i couldn't get the device name of it, but the vendor name is working okay...
i wanna commend you wholeheartedly for saving my job, i'll also like to spend time to improve this library and maintain it if possible.
please include a buyMeCoffee link so people who find it worthy like me can send you a token.
thanks
Dremo

**Comment by tejmagar** [comment]
Hi, thank you for your feedback and suggestions.
Sometimes the connected devices may return an IP Address instead of a hostname, you can check if the IP address and hostname are the same by:
`deviceItem.isDeviceNameAndIpAddressSame();`

Currently, there are three error codes (IP_ADDRESS_NULL, INVALID_TIMEOUT, UNKNOWN_ERROR)
So, by comparing error codes, developers can give custom messages to the user.

IP_ADDRESS_NULL may be due to the user may not have connected to the internet, 
INVALID_TIMOUT is when setTimeout is set to zero
UNKNOWN_ERROR may be caused when the thread is interrupted.

So, please always check if the device is connected to the WiFi before calling `deviceFinder.start();`

**Comment by AbGhost-cyber** [comment]
i get it now, i'll look into the library when i get home, i think the library should implement this instead of the developer checking the connection manually, i'll try to push some code later
thanks a lot bro, and yes i've seen the link... i'll buy you a coffee soon
